### ISSUE TITLE
error UNHANDLED REJECTION

### ISSUE THREAD

**Issue by ghost** [angeloocana/gatsby-starter-default-i18n#3] opened 2017-10-31 04:05 UTC
Hi angeloocana,

I have issue while I run i18n plugin.

```
error UNHANDLED REJECTION


  TypeError: Cannot read property 'jsonName' of undefined
  
  - pages-writer.js:79 
    [lazum3-gatsby]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:    79:36
  
  - Array.forEach
  
  - pages-writer.js:70 _callee$
    [lazum3-gatsby]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:    70:19
  
  - pages-writer.js:150 writePages
    [lazum3-gatsby]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:    150:17
  
  - index.js:450 _callee$
    [lazum3-gatsby]/[gatsby]/dist/bootstrap/index.js:450:20
  
  - next_tick.js:131 _combinedTickCallback
    internal/process/next_tick.js:131:7
  
  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9
```

**Comment by angeloocana** [comment] 2017-11-01 23:55
Hi @luannguyen252 

Thanks for trying out the starter and opening the issue! =D

I could not reproduce the error :/ 

Can I see your code?

Did you clone the project or used `gatsby new `?

Are you using yarn or npm?

What changes did you do to the project?


I'd love to help =D

**Comment by arthur31416** [comment] 2017-11-24 12:27
Hi 

I got the same issue and "solved" it by changing `useLangKeyLayout: true` to `useLangKeyLayout: false` in `gatsby-config.js`.

I don't know what this option is supposed to do.

EDIT: now I know what this option is for :). I forgot to use the `en.js` and `pt.js` in the `Layouts` folder. Now everything works fine.

**Comment by angeloocana** [comment] 2017-11-24 13:59
@arthur31416 Awesome!
If you have any ideas to improve the docs, I`d love Pull Requests =D

@luannguyen252  I`m closing this issue, no answers for 23 days.
Please feel free to reopen anytime, I`d love to help!

**Closed as completed by angeloocana** 2017-11-24 13:59 UTC
